version: '3'

services:

  postgres:
    build: /Users/N356976/Downloads/kafka-producer/build/Postgres/
    volumes:
      - db-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: N356976
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    restart: always
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    restart: always
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "hi_ertekin:1:3"
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  consumer:
    build: /Users/N356976/Downloads/kafka-consumer/
    container_name: consumer
    ports:
      - "8088:8088"
    depends_on:
      - kafka

  producer:
    build: /Users/N356976/Downloads/kafka-producer/
    container_name: producer
    ports:
      - "8085:8085"
    depends_on:
      - kafka
volumes:
  db-data:
